name: Actualización de Insights de Facebook Ads

on:
  schedule:
    # Se ejecuta cada hora (al minuto 0)
    - cron: "0 * * * *"
  workflow_dispatch:  # Permite ejecución manual

jobs:
  update-insights:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Crear archivo de credenciales para Google Sheets
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        run: echo "$GOOGLE_SHEETS_CREDENTIALS" > autosemaforo-cd96ce9df97b.json

      - name: Ejecutar script de actualización
        run: python main.py
