name: Facebook Ads Sync Hourly

on:
  schedule:
    - cron: '0 * * * *'  # Ejecuta cada hora en el minuto 0 (UTC)
  workflow_dispatch:     # Permite ejecución manual desde la UI de GitHub

jobs:
  run-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/autosemaforo-f3745e16ca62.json
        run: python main2.py